version: '3'
services:
  directus:
    image: directus/directus:11.5.1
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      KEY: 'kobizo-test-key-2025' 
      SECRET: 'kobizo-test-secret-2025'
      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'adminpass'
      DB_CLIENT: 'sqlite3'
      DB_FILENAME: '/directus/database/data.db'
      WEBSOCKETS_ENABLED: "true"